-- ============================================================================
-- Market Data Tables Setup for Investment Strategy Example
-- ============================================================================
-- Description: Creates tables needed for the non-ML investment strategy example
-- Execute as: ACCOUNTADMIN or role with appropriate privileges
-- ============================================================================

-- Note: This script adds market data tables to the existing environment setup.
-- Run after the environment setup scripts (01-04).

-- ============================================================================
-- DEV ENVIRONMENT - Market Data
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE DEV_WH_XS;

-- Raw market data table
CREATE TABLE IF NOT EXISTS DEV_RAW_DB.PUBLIC.MARKET_DATA (
    ASSET_ID VARCHAR(20) NOT NULL,
    DATE DATE NOT NULL,
    OPEN_PRICE DECIMAL(18,4),
    HIGH_PRICE DECIMAL(18,4),
    LOW_PRICE DECIMAL(18,4),
    CLOSE_PRICE DECIMAL(18,4),
    VOLUME BIGINT,
    -- Pre-calculated indicators (in production, these would be calculated via DAG)
    RSI_14 DECIMAL(10,4),
    MA_20 DECIMAL(18,4),
    MA_50 DECIMAL(18,4),
    VOLATILITY_20 DECIMAL(10,6),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ASSET_ID, DATE)
)
COMMENT = 'DEV: Raw market price data with technical indicators';

-- Trading signals output table
CREATE TABLE IF NOT EXISTS DEV_ML_DB.OUTPUT.TRADING_SIGNALS (
    ASSET_ID VARCHAR(20),
    SIGNAL VARCHAR(10),
    SIGNAL_STRENGTH DECIMAL(5,4),
    POSITION_SIZE DECIMAL(5,4),
    REASONING VARCHAR(1000),
    SIGNAL_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STRATEGY_VERSION VARCHAR(50)
)
COMMENT = 'DEV: Trading signals generated by investment strategy';

-- Strategy-specific stages
CREATE STAGE IF NOT EXISTS DEV_ML_DB.PIPELINES.STRATEGY_CODE_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'DEV: Storage for strategy Python code';

CREATE STAGE IF NOT EXISTS DEV_ML_DB.PIPELINES.STRATEGY_MODELS_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'DEV: Storage for registered strategy models';

-- Insert sample market data
INSERT INTO DEV_RAW_DB.PUBLIC.MARKET_DATA 
(ASSET_ID, DATE, OPEN_PRICE, HIGH_PRICE, LOW_PRICE, CLOSE_PRICE, VOLUME, RSI_14, MA_20, MA_50, VOLATILITY_20)
SELECT 
    asset_id,
    DATEADD(day, -seq, CURRENT_DATE()) AS DATE,
    base_price * (1 + UNIFORM(-0.02, 0.02, RANDOM())) AS OPEN_PRICE,
    base_price * (1 + UNIFORM(0, 0.03, RANDOM())) AS HIGH_PRICE,
    base_price * (1 + UNIFORM(-0.03, 0, RANDOM())) AS LOW_PRICE,
    base_price * (1 + UNIFORM(-0.02, 0.02, RANDOM())) AS CLOSE_PRICE,
    UNIFORM(1000000, 50000000, RANDOM()) AS VOLUME,
    UNIFORM(20, 80, RANDOM()) AS RSI_14,
    base_price * (1 + UNIFORM(-0.05, 0.05, RANDOM())) AS MA_20,
    base_price * (1 + UNIFORM(-0.08, 0.08, RANDOM())) AS MA_50,
    UNIFORM(0.15, 0.45, RANDOM()) AS VOLATILITY_20
FROM (
    SELECT 'AAPL' AS asset_id, 175.00 AS base_price
    UNION ALL SELECT 'MSFT', 380.00
    UNION ALL SELECT 'GOOGL', 140.00
    UNION ALL SELECT 'AMZN', 180.00
    UNION ALL SELECT 'NVDA', 480.00
    UNION ALL SELECT 'META', 350.00
    UNION ALL SELECT 'TSLA', 250.00
    UNION ALL SELECT 'JPM', 170.00
    UNION ALL SELECT 'V', 280.00
    UNION ALL SELECT 'JNJ', 160.00
) assets
CROSS JOIN (SELECT SEQ4() AS seq FROM TABLE(GENERATOR(ROWCOUNT => 100))) dates;

SELECT 'DEV Market Data Setup Complete!' AS STATUS, 
       COUNT(*) AS RECORDS 
FROM DEV_RAW_DB.PUBLIC.MARKET_DATA;

-- ============================================================================
-- SIT ENVIRONMENT - Market Data
-- ============================================================================

USE WAREHOUSE SIT_WH_S;

CREATE TABLE IF NOT EXISTS SIT_RAW_DB.PUBLIC.MARKET_DATA (
    ASSET_ID VARCHAR(20) NOT NULL,
    DATE DATE NOT NULL,
    OPEN_PRICE DECIMAL(18,4),
    HIGH_PRICE DECIMAL(18,4),
    LOW_PRICE DECIMAL(18,4),
    CLOSE_PRICE DECIMAL(18,4),
    VOLUME BIGINT,
    RSI_14 DECIMAL(10,4),
    MA_20 DECIMAL(18,4),
    MA_50 DECIMAL(18,4),
    VOLATILITY_20 DECIMAL(10,6),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ASSET_ID, DATE)
)
COMMENT = 'SIT: Raw market price data with technical indicators';

CREATE TABLE IF NOT EXISTS SIT_ML_DB.OUTPUT.TRADING_SIGNALS (
    ASSET_ID VARCHAR(20),
    SIGNAL VARCHAR(10),
    SIGNAL_STRENGTH DECIMAL(5,4),
    POSITION_SIZE DECIMAL(5,4),
    REASONING VARCHAR(1000),
    SIGNAL_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STRATEGY_VERSION VARCHAR(50)
)
COMMENT = 'SIT: Trading signals generated by investment strategy';

CREATE STAGE IF NOT EXISTS SIT_ML_DB.PIPELINES.STRATEGY_CODE_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'SIT: Storage for strategy Python code';

CREATE STAGE IF NOT EXISTS SIT_ML_DB.PIPELINES.STRATEGY_MODELS_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'SIT: Storage for registered strategy models';

-- Clone sample data from DEV
INSERT INTO SIT_RAW_DB.PUBLIC.MARKET_DATA 
SELECT * FROM DEV_RAW_DB.PUBLIC.MARKET_DATA;

SELECT 'SIT Market Data Setup Complete!' AS STATUS;

-- ============================================================================
-- UAT ENVIRONMENT - Market Data
-- ============================================================================

USE WAREHOUSE UAT_WH_M;

CREATE TABLE IF NOT EXISTS UAT_RAW_DB.PUBLIC.MARKET_DATA (
    ASSET_ID VARCHAR(20) NOT NULL,
    DATE DATE NOT NULL,
    OPEN_PRICE DECIMAL(18,4),
    HIGH_PRICE DECIMAL(18,4),
    LOW_PRICE DECIMAL(18,4),
    CLOSE_PRICE DECIMAL(18,4),
    VOLUME BIGINT,
    RSI_14 DECIMAL(10,4),
    MA_20 DECIMAL(18,4),
    MA_50 DECIMAL(18,4),
    VOLATILITY_20 DECIMAL(10,6),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ASSET_ID, DATE)
)
COMMENT = 'UAT: Raw market price data with technical indicators';

CREATE TABLE IF NOT EXISTS UAT_ML_DB.OUTPUT.TRADING_SIGNALS (
    ASSET_ID VARCHAR(20),
    SIGNAL VARCHAR(10),
    SIGNAL_STRENGTH DECIMAL(5,4),
    POSITION_SIZE DECIMAL(5,4),
    REASONING VARCHAR(1000),
    SIGNAL_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STRATEGY_VERSION VARCHAR(50)
)
COMMENT = 'UAT: Trading signals generated by investment strategy';

CREATE STAGE IF NOT EXISTS UAT_ML_DB.PIPELINES.STRATEGY_CODE_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'UAT: Storage for strategy Python code';

CREATE STAGE IF NOT EXISTS UAT_ML_DB.PIPELINES.STRATEGY_MODELS_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'UAT: Storage for registered strategy models';

-- Clone sample data from DEV
INSERT INTO UAT_RAW_DB.PUBLIC.MARKET_DATA 
SELECT * FROM DEV_RAW_DB.PUBLIC.MARKET_DATA;

SELECT 'UAT Market Data Setup Complete!' AS STATUS;

-- ============================================================================
-- PRD ENVIRONMENT - Market Data
-- ============================================================================

USE WAREHOUSE PRD_WH_L;

CREATE TABLE IF NOT EXISTS PRD_RAW_DB.PUBLIC.MARKET_DATA (
    ASSET_ID VARCHAR(20) NOT NULL,
    DATE DATE NOT NULL,
    OPEN_PRICE DECIMAL(18,4),
    HIGH_PRICE DECIMAL(18,4),
    LOW_PRICE DECIMAL(18,4),
    CLOSE_PRICE DECIMAL(18,4),
    VOLUME BIGINT,
    RSI_14 DECIMAL(10,4),
    MA_20 DECIMAL(18,4),
    MA_50 DECIMAL(18,4),
    VOLATILITY_20 DECIMAL(10,6),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ASSET_ID, DATE)
)
DATA_RETENTION_TIME_IN_DAYS = 90
COMMENT = 'PRD: Raw market price data with technical indicators';

CREATE TABLE IF NOT EXISTS PRD_ML_DB.OUTPUT.TRADING_SIGNALS (
    ASSET_ID VARCHAR(20),
    SIGNAL VARCHAR(10),
    SIGNAL_STRENGTH DECIMAL(5,4),
    POSITION_SIZE DECIMAL(5,4),
    REASONING VARCHAR(1000),
    SIGNAL_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STRATEGY_VERSION VARCHAR(50)
)
DATA_RETENTION_TIME_IN_DAYS = 30
COMMENT = 'PRD: Trading signals generated by investment strategy';

CREATE TABLE IF NOT EXISTS PRD_ML_DB.OUTPUT.TRADING_SIGNALS_HISTORY (
    ASSET_ID VARCHAR(20),
    SIGNAL VARCHAR(10),
    SIGNAL_STRENGTH DECIMAL(5,4),
    POSITION_SIZE DECIMAL(5,4),
    REASONING VARCHAR(1000),
    SIGNAL_TIMESTAMP TIMESTAMP_NTZ,
    STRATEGY_VERSION VARCHAR(50),
    ARCHIVED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'PRD: Historical trading signals archive';

CREATE STAGE IF NOT EXISTS PRD_ML_DB.PIPELINES.STRATEGY_CODE_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'PRD: Storage for strategy Python code';

CREATE STAGE IF NOT EXISTS PRD_ML_DB.PIPELINES.STRATEGY_MODELS_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'PRD: Storage for registered strategy models';

-- Monitoring views for trading signals
CREATE OR REPLACE VIEW PRD_ML_DB.OUTPUT.RECENT_TRADING_SIGNALS AS
SELECT 
    ASSET_ID,
    SIGNAL,
    SIGNAL_STRENGTH,
    POSITION_SIZE,
    REASONING,
    SIGNAL_TIMESTAMP,
    STRATEGY_VERSION
FROM PRD_ML_DB.OUTPUT.TRADING_SIGNALS
WHERE SIGNAL_TIMESTAMP >= DATEADD(DAY, -7, CURRENT_TIMESTAMP())
ORDER BY SIGNAL_TIMESTAMP DESC;

CREATE OR REPLACE VIEW PRD_ML_DB.OUTPUT.SIGNAL_ANALYTICS AS
SELECT 
    DATE_TRUNC('DAY', SIGNAL_TIMESTAMP) AS SIGNAL_DATE,
    STRATEGY_VERSION,
    SIGNAL,
    COUNT(*) AS SIGNAL_COUNT,
    AVG(SIGNAL_STRENGTH) AS AVG_STRENGTH,
    SUM(POSITION_SIZE) AS TOTAL_POSITION
FROM PRD_ML_DB.OUTPUT.TRADING_SIGNALS
GROUP BY 1, 2, 3
ORDER BY 1 DESC, 2, 3;

SELECT 'PRD Market Data Setup Complete!' AS STATUS;
SELECT 'NOTE: PRD data should come from market data feeds' AS INFO;

-- ============================================================================
-- SUMMARY
-- ============================================================================

SELECT 'Market Data Tables Setup Complete!' AS STATUS;
SELECT 'Run this script AFTER the main environment setup scripts' AS NOTE;

