-- ============================================================================
-- ALL-IN-ONE SETUP: Complete ML Pipeline Infrastructure
-- ============================================================================
-- Description: Sets up all environments (DEV, SIT, UAT, PRD) and security in one script
-- Execute as: ACCOUNTADMIN
-- Duration: ~3-4 minutes
-- ============================================================================
-- 
-- ⚠️  WARNING: This script will create multiple databases, warehouses, and roles
-- Review each section before execution in production environments
--
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- ============================================================================
-- SECTION 1: WAREHOUSES
-- ============================================================================

SELECT '========================================' AS INFO;
SELECT 'Creating Warehouses...' AS STEP;
SELECT '========================================' AS INFO;

CREATE WAREHOUSE IF NOT EXISTS DEV_WH_XS
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Development warehouse for ML pipelines - XS size for cost efficiency';

CREATE WAREHOUSE IF NOT EXISTS SIT_WH_S
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'SIT warehouse for ML pipelines - S size for integration testing';

CREATE WAREHOUSE IF NOT EXISTS UAT_WH_M
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 180
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'UAT warehouse for ML pipelines - M size for pre-production validation';

CREATE WAREHOUSE IF NOT EXISTS PRD_WH_L
    WAREHOUSE_SIZE = 'LARGE'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Production warehouse for ML pipelines - L size for production workloads';

SELECT 'Warehouses created successfully ✓' AS STATUS;

-- ============================================================================
-- SECTION 2: DEV ENVIRONMENT
-- ============================================================================

SELECT '========================================' AS INFO;
SELECT 'Setting up DEV Environment...' AS STEP;
SELECT '========================================' AS INFO;

USE WAREHOUSE DEV_WH_XS;

-- DEV Raw Database
CREATE DATABASE IF NOT EXISTS DEV_RAW_DB COMMENT = 'Development - Raw data source database';
CREATE SCHEMA IF NOT EXISTS DEV_RAW_DB.PUBLIC COMMENT = 'Raw data schema for development';

CREATE OR REPLACE TABLE DEV_RAW_DB.PUBLIC.CUSTOMERS (
    CUSTOMER_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(200),
    AGE INTEGER,
    ACCOUNT_BALANCE DECIMAL(18,2),
    TENURE_MONTHS INTEGER,
    NUM_PRODUCTS INTEGER,
    HAS_CREDIT_CARD BOOLEAN,
    IS_ACTIVE_MEMBER BOOLEAN,
    TARGET_LABEL INTEGER,
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'DEV: Raw customer data for churn prediction';

-- DEV ML Database
CREATE DATABASE IF NOT EXISTS DEV_ML_DB COMMENT = 'Development - ML pipeline database';
CREATE SCHEMA IF NOT EXISTS DEV_ML_DB.PIPELINES COMMENT = 'DEV: Contains ML pipeline tasks and DAG definitions';
CREATE SCHEMA IF NOT EXISTS DEV_ML_DB.FEATURES COMMENT = 'DEV: Feature Store objects and feature views';
CREATE SCHEMA IF NOT EXISTS DEV_ML_DB.OUTPUT COMMENT = 'DEV: ML inference outputs and predictions';

-- DEV Stages
CREATE STAGE IF NOT EXISTS DEV_ML_DB.PIPELINES.ML_CODE_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'DEV: Storage for Python ML logic files';

CREATE STAGE IF NOT EXISTS DEV_ML_DB.PIPELINES.MODELS_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'DEV: Storage for trained ML models';

-- DEV Output Table
CREATE TABLE IF NOT EXISTS DEV_ML_DB.OUTPUT.PREDICTIONS (
    CUSTOMER_ID VARCHAR(50),
    PREDICTION INTEGER,
    PREDICTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODEL_VERSION VARCHAR(50),
    CONFIDENCE_SCORE DECIMAL(5,4)
) COMMENT = 'DEV: ML model prediction outputs';

-- DEV Sample Data
INSERT INTO DEV_RAW_DB.PUBLIC.CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, AGE, ACCOUNT_BALANCE, TENURE_MONTHS, NUM_PRODUCTS, HAS_CREDIT_CARD, IS_ACTIVE_MEMBER, TARGET_LABEL)
SELECT 
    'CUST_' || SEQ4() AS CUSTOMER_ID,
    'Customer ' || SEQ4() AS CUSTOMER_NAME,
    UNIFORM(18, 75, RANDOM()) AS AGE,
    UNIFORM(0, 100000, RANDOM()) AS ACCOUNT_BALANCE,
    UNIFORM(0, 120, RANDOM()) AS TENURE_MONTHS,
    UNIFORM(1, 4, RANDOM()) AS NUM_PRODUCTS,
    CASE WHEN UNIFORM(0, 1, RANDOM()) = 1 THEN TRUE ELSE FALSE END AS HAS_CREDIT_CARD,
    CASE WHEN UNIFORM(0, 1, RANDOM()) = 1 THEN TRUE ELSE FALSE END AS IS_ACTIVE_MEMBER,
    CASE WHEN UNIFORM(0, 10, RANDOM()) > 8 THEN 1 ELSE 0 END AS TARGET_LABEL
FROM TABLE(GENERATOR(ROWCOUNT => 1000));

SELECT 'DEV Environment created successfully ✓' AS STATUS;

-- ============================================================================
-- SECTION 3: SIT ENVIRONMENT
-- ============================================================================

SELECT '========================================' AS INFO;
SELECT 'Setting up SIT Environment...' AS STEP;
SELECT '========================================' AS INFO;

USE WAREHOUSE SIT_WH_S;

-- SIT Raw Database
CREATE DATABASE IF NOT EXISTS SIT_RAW_DB COMMENT = 'SIT - Raw data source database';
CREATE SCHEMA IF NOT EXISTS SIT_RAW_DB.PUBLIC COMMENT = 'Raw data schema for SIT';

CREATE OR REPLACE TABLE SIT_RAW_DB.PUBLIC.CUSTOMERS (
    CUSTOMER_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(200),
    AGE INTEGER,
    ACCOUNT_BALANCE DECIMAL(18,2),
    TENURE_MONTHS INTEGER,
    NUM_PRODUCTS INTEGER,
    HAS_CREDIT_CARD BOOLEAN,
    IS_ACTIVE_MEMBER BOOLEAN,
    TARGET_LABEL INTEGER,
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'SIT: Raw customer data for churn prediction';

-- SIT ML Database
CREATE DATABASE IF NOT EXISTS SIT_ML_DB COMMENT = 'SIT - ML pipeline database';
CREATE SCHEMA IF NOT EXISTS SIT_ML_DB.PIPELINES COMMENT = 'SIT: Contains ML pipeline tasks and DAG definitions';
CREATE SCHEMA IF NOT EXISTS SIT_ML_DB.FEATURES COMMENT = 'SIT: Feature Store objects and feature views';
CREATE SCHEMA IF NOT EXISTS SIT_ML_DB.OUTPUT COMMENT = 'SIT: ML inference outputs and predictions';

-- SIT Stages
CREATE STAGE IF NOT EXISTS SIT_ML_DB.PIPELINES.ML_CODE_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'SIT: Storage for Python ML logic files';

CREATE STAGE IF NOT EXISTS SIT_ML_DB.PIPELINES.MODELS_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'SIT: Storage for trained ML models';

-- SIT Output Table
CREATE TABLE IF NOT EXISTS SIT_ML_DB.OUTPUT.PREDICTIONS (
    CUSTOMER_ID VARCHAR(50),
    PREDICTION INTEGER,
    PREDICTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODEL_VERSION VARCHAR(50),
    CONFIDENCE_SCORE DECIMAL(5,4)
) COMMENT = 'SIT: ML model prediction outputs';

-- SIT Sample Data
INSERT INTO SIT_RAW_DB.PUBLIC.CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, AGE, ACCOUNT_BALANCE, TENURE_MONTHS, NUM_PRODUCTS, HAS_CREDIT_CARD, IS_ACTIVE_MEMBER, TARGET_LABEL)
SELECT 
    'CUST_' || SEQ4() AS CUSTOMER_ID,
    'Customer ' || SEQ4() AS CUSTOMER_NAME,
    UNIFORM(18, 75, RANDOM()) AS AGE,
    UNIFORM(0, 100000, RANDOM()) AS ACCOUNT_BALANCE,
    UNIFORM(0, 120, RANDOM()) AS TENURE_MONTHS,
    UNIFORM(1, 4, RANDOM()) AS NUM_PRODUCTS,
    CASE WHEN UNIFORM(0, 1, RANDOM()) = 1 THEN TRUE ELSE FALSE END AS HAS_CREDIT_CARD,
    CASE WHEN UNIFORM(0, 1, RANDOM()) = 1 THEN TRUE ELSE FALSE END AS IS_ACTIVE_MEMBER,
    CASE WHEN UNIFORM(0, 10, RANDOM()) > 8 THEN 1 ELSE 0 END AS TARGET_LABEL
FROM TABLE(GENERATOR(ROWCOUNT => 5000));

SELECT 'SIT Environment created successfully ✓' AS STATUS;

-- ============================================================================
-- SECTION 4: UAT ENVIRONMENT
-- ============================================================================

SELECT '========================================' AS INFO;
SELECT 'Setting up UAT Environment...' AS STEP;
SELECT '========================================' AS INFO;

USE WAREHOUSE UAT_WH_M;

-- UAT Raw Database
CREATE DATABASE IF NOT EXISTS UAT_RAW_DB COMMENT = 'UAT - Raw data source database';
CREATE SCHEMA IF NOT EXISTS UAT_RAW_DB.PUBLIC COMMENT = 'Raw data schema for UAT';

CREATE OR REPLACE TABLE UAT_RAW_DB.PUBLIC.CUSTOMERS (
    CUSTOMER_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(200),
    AGE INTEGER,
    ACCOUNT_BALANCE DECIMAL(18,2),
    TENURE_MONTHS INTEGER,
    NUM_PRODUCTS INTEGER,
    HAS_CREDIT_CARD BOOLEAN,
    IS_ACTIVE_MEMBER BOOLEAN,
    TARGET_LABEL INTEGER,
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'UAT: Raw customer data for churn prediction';

-- UAT ML Database
CREATE DATABASE IF NOT EXISTS UAT_ML_DB COMMENT = 'UAT - ML pipeline database';
CREATE SCHEMA IF NOT EXISTS UAT_ML_DB.PIPELINES COMMENT = 'UAT: Contains ML pipeline tasks and DAG definitions';
CREATE SCHEMA IF NOT EXISTS UAT_ML_DB.FEATURES COMMENT = 'UAT: Feature Store objects and feature views';
CREATE SCHEMA IF NOT EXISTS UAT_ML_DB.OUTPUT COMMENT = 'UAT: ML inference outputs and predictions';

-- UAT Stages
CREATE STAGE IF NOT EXISTS UAT_ML_DB.PIPELINES.ML_CODE_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'UAT: Storage for Python ML logic files';

CREATE STAGE IF NOT EXISTS UAT_ML_DB.PIPELINES.MODELS_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'UAT: Storage for trained ML models';

-- UAT Output Tables
CREATE TABLE IF NOT EXISTS UAT_ML_DB.OUTPUT.PREDICTIONS (
    CUSTOMER_ID VARCHAR(50),
    PREDICTION INTEGER,
    PREDICTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODEL_VERSION VARCHAR(50),
    CONFIDENCE_SCORE DECIMAL(5,4)
) DATA_RETENTION_TIME_IN_DAYS = 3
COMMENT = 'UAT: ML model prediction outputs';

CREATE TABLE IF NOT EXISTS UAT_ML_DB.OUTPUT.UAT_VALIDATION_METRICS (
    TEST_RUN_ID VARCHAR(100),
    TEST_NAME VARCHAR(200),
    METRIC_NAME VARCHAR(100),
    METRIC_VALUE DECIMAL(18,6),
    TEST_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS VARCHAR(20),
    NOTES VARCHAR(1000)
) COMMENT = 'UAT: Validation metrics for pre-production testing';

-- UAT Sample Data (production-like volume)
INSERT INTO UAT_RAW_DB.PUBLIC.CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, AGE, ACCOUNT_BALANCE, TENURE_MONTHS, NUM_PRODUCTS, HAS_CREDIT_CARD, IS_ACTIVE_MEMBER, TARGET_LABEL)
SELECT 
    'CUST_' || SEQ4() AS CUSTOMER_ID,
    'Customer ' || SEQ4() AS CUSTOMER_NAME,
    UNIFORM(18, 75, RANDOM()) AS AGE,
    UNIFORM(0, 100000, RANDOM()) AS ACCOUNT_BALANCE,
    UNIFORM(0, 120, RANDOM()) AS TENURE_MONTHS,
    UNIFORM(1, 4, RANDOM()) AS NUM_PRODUCTS,
    CASE WHEN UNIFORM(0, 1, RANDOM()) = 1 THEN TRUE ELSE FALSE END AS HAS_CREDIT_CARD,
    CASE WHEN UNIFORM(0, 1, RANDOM()) = 1 THEN TRUE ELSE FALSE END AS IS_ACTIVE_MEMBER,
    CASE WHEN UNIFORM(0, 10, RANDOM()) > 8 THEN 1 ELSE 0 END AS TARGET_LABEL
FROM TABLE(GENERATOR(ROWCOUNT => 10000));

-- UAT Monitoring Views
CREATE OR REPLACE VIEW UAT_ML_DB.OUTPUT.RECENT_PREDICTIONS AS
SELECT CUSTOMER_ID, PREDICTION, PREDICTION_TIMESTAMP, MODEL_VERSION, CONFIDENCE_SCORE
FROM UAT_ML_DB.OUTPUT.PREDICTIONS
WHERE PREDICTION_TIMESTAMP >= DATEADD(DAY, -3, CURRENT_TIMESTAMP())
ORDER BY PREDICTION_TIMESTAMP DESC;

SELECT 'UAT Environment created successfully ✓' AS STATUS;

-- ============================================================================
-- SECTION 5: PRD ENVIRONMENT
-- ============================================================================

SELECT '========================================' AS INFO;
SELECT 'Setting up PRD Environment...' AS STEP;
SELECT '========================================' AS INFO;

USE WAREHOUSE PRD_WH_L;

-- PRD Raw Database
CREATE DATABASE IF NOT EXISTS PRD_RAW_DB COMMENT = 'PRODUCTION - Raw data source database';
CREATE SCHEMA IF NOT EXISTS PRD_RAW_DB.PUBLIC COMMENT = 'Raw data schema for production';

CREATE TABLE IF NOT EXISTS PRD_RAW_DB.PUBLIC.CUSTOMERS (
    CUSTOMER_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(200),
    AGE INTEGER,
    ACCOUNT_BALANCE DECIMAL(18,2),
    TENURE_MONTHS INTEGER,
    NUM_PRODUCTS INTEGER,
    HAS_CREDIT_CARD BOOLEAN,
    IS_ACTIVE_MEMBER BOOLEAN,
    TARGET_LABEL INTEGER,
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'PRODUCTION: Raw customer data for churn prediction';

-- PRD ML Database
CREATE DATABASE IF NOT EXISTS PRD_ML_DB COMMENT = 'PRODUCTION - ML pipeline database';
CREATE SCHEMA IF NOT EXISTS PRD_ML_DB.PIPELINES COMMENT = 'PRD: Contains ML pipeline tasks and DAG definitions';
CREATE SCHEMA IF NOT EXISTS PRD_ML_DB.FEATURES COMMENT = 'PRD: Feature Store objects and feature views';
CREATE SCHEMA IF NOT EXISTS PRD_ML_DB.OUTPUT COMMENT = 'PRD: ML inference outputs and predictions';

-- PRD Stages
CREATE STAGE IF NOT EXISTS PRD_ML_DB.PIPELINES.ML_CODE_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'PRD: Storage for Python ML logic files';

CREATE STAGE IF NOT EXISTS PRD_ML_DB.PIPELINES.MODELS_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'PRD: Storage for trained ML models';

-- PRD Output Tables
CREATE TABLE IF NOT EXISTS PRD_ML_DB.OUTPUT.PREDICTIONS (
    CUSTOMER_ID VARCHAR(50),
    PREDICTION INTEGER,
    PREDICTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODEL_VERSION VARCHAR(50),
    CONFIDENCE_SCORE DECIMAL(5,4)
) DATA_RETENTION_TIME_IN_DAYS = 7
COMMENT = 'PRODUCTION: ML model prediction outputs';

CREATE TABLE IF NOT EXISTS PRD_ML_DB.OUTPUT.PREDICTIONS_HISTORY (
    CUSTOMER_ID VARCHAR(50),
    PREDICTION INTEGER,
    PREDICTION_TIMESTAMP TIMESTAMP_NTZ,
    MODEL_VERSION VARCHAR(50),
    CONFIDENCE_SCORE DECIMAL(5,4),
    ARCHIVED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'PRODUCTION: Historical archive of predictions';

-- PRD Monitoring Views
CREATE OR REPLACE VIEW PRD_ML_DB.OUTPUT.RECENT_PREDICTIONS AS
SELECT CUSTOMER_ID, PREDICTION, PREDICTION_TIMESTAMP, MODEL_VERSION, CONFIDENCE_SCORE
FROM PRD_ML_DB.OUTPUT.PREDICTIONS
WHERE PREDICTION_TIMESTAMP >= DATEADD(DAY, -7, CURRENT_TIMESTAMP())
ORDER BY PREDICTION_TIMESTAMP DESC;

CREATE OR REPLACE VIEW PRD_ML_DB.OUTPUT.PREDICTION_STATS AS
SELECT 
    DATE_TRUNC('DAY', PREDICTION_TIMESTAMP) AS PREDICTION_DATE,
    MODEL_VERSION,
    COUNT(*) AS TOTAL_PREDICTIONS,
    SUM(CASE WHEN PREDICTION = 1 THEN 1 ELSE 0 END) AS CHURN_PREDICTIONS,
    SUM(CASE WHEN PREDICTION = 0 THEN 1 ELSE 0 END) AS RETAINED_PREDICTIONS,
    AVG(CONFIDENCE_SCORE) AS AVG_CONFIDENCE,
    MIN(CONFIDENCE_SCORE) AS MIN_CONFIDENCE,
    MAX(CONFIDENCE_SCORE) AS MAX_CONFIDENCE
FROM PRD_ML_DB.OUTPUT.PREDICTIONS
GROUP BY 1, 2
ORDER BY 1 DESC, 2;

SELECT 'PRD Environment created successfully ✓' AS STATUS;
SELECT '⚠️  NOTE: Production data should be loaded via ETL pipelines' AS INFO;

-- ============================================================================
-- SECTION 6: ROLES AND SECURITY
-- ============================================================================

SELECT '========================================' AS INFO;
SELECT 'Setting up Roles and Security...' AS STEP;
SELECT '========================================' AS INFO;

USE ROLE SECURITYADMIN;

-- Create Roles
CREATE ROLE IF NOT EXISTS ML_DEV_ROLE COMMENT = 'Role for ML developers working in DEV environment';
CREATE ROLE IF NOT EXISTS ML_SIT_ROLE COMMENT = 'Role for ML testing in SIT environment';
CREATE ROLE IF NOT EXISTS ML_UAT_ROLE COMMENT = 'Role for ML UAT pre-production validation';
CREATE ROLE IF NOT EXISTS ML_PRD_ROLE COMMENT = 'Role for ML production pipeline execution';
CREATE ROLE IF NOT EXISTS ML_CICD_ROLE COMMENT = 'Role for GitHub Actions CI/CD pipeline';

-- Role Hierarchy
GRANT ROLE ML_DEV_ROLE TO ROLE SYSADMIN;
GRANT ROLE ML_SIT_ROLE TO ROLE SYSADMIN;
GRANT ROLE ML_UAT_ROLE TO ROLE SYSADMIN;
GRANT ROLE ML_PRD_ROLE TO ROLE SYSADMIN;
GRANT ROLE ML_CICD_ROLE TO ROLE SYSADMIN;

GRANT ROLE ML_DEV_ROLE TO ROLE ML_CICD_ROLE;
GRANT ROLE ML_SIT_ROLE TO ROLE ML_CICD_ROLE;
GRANT ROLE ML_UAT_ROLE TO ROLE ML_CICD_ROLE;
GRANT ROLE ML_PRD_ROLE TO ROLE ML_CICD_ROLE;

USE ROLE ACCOUNTADMIN;

-- DEV Grants
GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE DEV_WH_XS TO ROLE ML_DEV_ROLE;
GRANT USAGE ON DATABASE DEV_RAW_DB TO ROLE ML_DEV_ROLE;
GRANT USAGE ON SCHEMA DEV_RAW_DB.PUBLIC TO ROLE ML_DEV_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DEV_RAW_DB.PUBLIC TO ROLE ML_DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEV_RAW_DB.PUBLIC TO ROLE ML_DEV_ROLE;

GRANT ALL ON DATABASE DEV_ML_DB TO ROLE ML_DEV_ROLE;
GRANT ALL ON SCHEMA DEV_ML_DB.PIPELINES TO ROLE ML_DEV_ROLE;
GRANT ALL ON SCHEMA DEV_ML_DB.FEATURES TO ROLE ML_DEV_ROLE;
GRANT ALL ON SCHEMA DEV_ML_DB.OUTPUT TO ROLE ML_DEV_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA DEV_ML_DB.PIPELINES TO ROLE ML_DEV_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA DEV_ML_DB.FEATURES TO ROLE ML_DEV_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA DEV_ML_DB.OUTPUT TO ROLE ML_DEV_ROLE;
GRANT ALL ON ALL STAGES IN SCHEMA DEV_ML_DB.PIPELINES TO ROLE ML_DEV_ROLE;

-- SIT Grants
GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE SIT_WH_S TO ROLE ML_SIT_ROLE;
GRANT USAGE ON DATABASE SIT_RAW_DB TO ROLE ML_SIT_ROLE;
GRANT USAGE ON SCHEMA SIT_RAW_DB.PUBLIC TO ROLE ML_SIT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SIT_RAW_DB.PUBLIC TO ROLE ML_SIT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SIT_RAW_DB.PUBLIC TO ROLE ML_SIT_ROLE;

GRANT ALL ON DATABASE SIT_ML_DB TO ROLE ML_SIT_ROLE;
GRANT ALL ON SCHEMA SIT_ML_DB.PIPELINES TO ROLE ML_SIT_ROLE;
GRANT ALL ON SCHEMA SIT_ML_DB.FEATURES TO ROLE ML_SIT_ROLE;
GRANT ALL ON SCHEMA SIT_ML_DB.OUTPUT TO ROLE ML_SIT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA SIT_ML_DB.PIPELINES TO ROLE ML_SIT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA SIT_ML_DB.FEATURES TO ROLE ML_SIT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA SIT_ML_DB.OUTPUT TO ROLE ML_SIT_ROLE;
GRANT ALL ON ALL STAGES IN SCHEMA SIT_ML_DB.PIPELINES TO ROLE ML_SIT_ROLE;

-- UAT Grants
GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE UAT_WH_M TO ROLE ML_UAT_ROLE;
GRANT USAGE ON DATABASE UAT_RAW_DB TO ROLE ML_UAT_ROLE;
GRANT USAGE ON SCHEMA UAT_RAW_DB.PUBLIC TO ROLE ML_UAT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA UAT_RAW_DB.PUBLIC TO ROLE ML_UAT_ROLE;
GRANT ALL ON DATABASE UAT_ML_DB TO ROLE ML_UAT_ROLE;
GRANT ALL ON SCHEMA UAT_ML_DB.PIPELINES TO ROLE ML_UAT_ROLE;
GRANT ALL ON SCHEMA UAT_ML_DB.FEATURES TO ROLE ML_UAT_ROLE;
GRANT ALL ON SCHEMA UAT_ML_DB.OUTPUT TO ROLE ML_UAT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA UAT_ML_DB.PIPELINES TO ROLE ML_UAT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA UAT_ML_DB.FEATURES TO ROLE ML_UAT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA UAT_ML_DB.OUTPUT TO ROLE ML_UAT_ROLE;
GRANT ALL ON ALL STAGES IN SCHEMA UAT_ML_DB.PIPELINES TO ROLE ML_UAT_ROLE;

-- PRD Grants
GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE PRD_WH_L TO ROLE ML_PRD_ROLE;
GRANT USAGE ON DATABASE PRD_RAW_DB TO ROLE ML_PRD_ROLE;
GRANT USAGE ON SCHEMA PRD_RAW_DB.PUBLIC TO ROLE ML_PRD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PRD_RAW_DB.PUBLIC TO ROLE ML_PRD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PRD_RAW_DB.PUBLIC TO ROLE ML_PRD_ROLE;

GRANT USAGE ON DATABASE PRD_ML_DB TO ROLE ML_PRD_ROLE;
GRANT ALL ON SCHEMA PRD_ML_DB.PIPELINES TO ROLE ML_PRD_ROLE;
GRANT USAGE ON SCHEMA PRD_ML_DB.FEATURES TO ROLE ML_PRD_ROLE;
GRANT USAGE ON SCHEMA PRD_ML_DB.OUTPUT TO ROLE ML_PRD_ROLE;
GRANT CREATE TABLE ON SCHEMA PRD_ML_DB.FEATURES TO ROLE ML_PRD_ROLE;
GRANT CREATE TABLE ON SCHEMA PRD_ML_DB.OUTPUT TO ROLE ML_PRD_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA PRD_ML_DB.PIPELINES TO ROLE ML_PRD_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA PRD_ML_DB.FEATURES TO ROLE ML_PRD_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA PRD_ML_DB.OUTPUT TO ROLE ML_PRD_ROLE;
GRANT ALL ON ALL STAGES IN SCHEMA PRD_ML_DB.PIPELINES TO ROLE ML_PRD_ROLE;

SELECT 'Roles and Security configured successfully ✓' AS STATUS;

-- ============================================================================
-- FINAL VERIFICATION
-- ============================================================================

SELECT '========================================' AS INFO;
SELECT 'Setup Complete! Running Verification...' AS STEP;
SELECT '========================================' AS INFO;

-- Summary Report
SELECT 
    '✓ Setup Complete' AS STATUS,
    'All environments configured' AS MESSAGE;

-- Databases
SELECT 'DATABASES' AS OBJECT_TYPE, COUNT(*) AS CREATED
FROM (
    SELECT DATABASE_NAME FROM INFORMATION_SCHEMA.DATABASES 
    WHERE DATABASE_NAME LIKE 'DEV_%' 
       OR DATABASE_NAME LIKE 'SIT_%' 
       OR DATABASE_NAME LIKE 'PRD_%'
);

-- Warehouses
SELECT 'WAREHOUSES' AS OBJECT_TYPE, COUNT(*) AS CREATED
FROM INFORMATION_SCHEMA.WAREHOUSES
WHERE WAREHOUSE_NAME IN ('DEV_WH_XS', 'SIT_WH_S', 'PRD_WH_L');

-- Roles
SHOW ROLES LIKE 'ML_%';

-- Sample Data Counts
SELECT 'DEV Sample Data' AS ENVIRONMENT, COUNT(*) AS RECORDS FROM DEV_RAW_DB.PUBLIC.CUSTOMERS
UNION ALL
SELECT 'SIT Sample Data' AS ENVIRONMENT, COUNT(*) AS RECORDS FROM SIT_RAW_DB.PUBLIC.CUSTOMERS
UNION ALL
SELECT 'UAT Sample Data' AS ENVIRONMENT, COUNT(*) AS RECORDS FROM UAT_RAW_DB.PUBLIC.CUSTOMERS
UNION ALL
SELECT 'PRD Sample Data' AS ENVIRONMENT, COUNT(*) AS RECORDS FROM PRD_RAW_DB.PUBLIC.CUSTOMERS;

-- ============================================================================
-- NEXT STEPS
-- ============================================================================

SELECT '========================================' AS INFO;
SELECT 'NEXT STEPS:' AS INFO;
SELECT '========================================' AS INFO;
SELECT '1. Grant roles to users: GRANT ROLE ML_DEV_ROLE TO USER <username>;' AS ACTION
UNION ALL
SELECT '2. Create CI/CD user with key-pair authentication' AS ACTION
UNION ALL
SELECT '3. Configure GitHub Secrets (SNOWFLAKE_ACCOUNT, SNOWFLAKE_USER, etc.)' AS ACTION
UNION ALL
SELECT '4. Deploy Python code via GitHub Actions workflow' AS ACTION
UNION ALL
SELECT '5. Verify DAG creation: SHOW TASKS IN SCHEMA DEV_ML_DB.PIPELINES;' AS ACTION;

SELECT '========================================' AS INFO;
SELECT '✅ All Done!' AS INFO;
SELECT '========================================' AS INFO;

